### ISSUE TITLE
VitaShell Settings menu

### ISSUE THREAD

**Issue by TheOfficialFloW** [TheOfficialFloW/VitaShell#96]
We need a settings menu.
- [x] Adding resources (colors/images) instead of using hard-coded values
- [ ] Adding the actual settings
- [ ] Audible feedback whenever user executes an action - Refer to #103 
- [ ] Battery Percentage - Refer to #97 
- [ ] Change Font Size
- [ ] Change Language
- [ ] Change FTP Port
- [x] Implement minimalistic design
- [ ] Remove .vpk after installation - Refer to #132 
- [ ] Scrolling

**Comment by theorywrong** [comment]
- Change Font SIze
- Change Language (maybe Japanese guys want to read VitaShell in english)
- Change FTP Port

**Comment by TheOfficialFloW** [comment]
I mean we need a GUI for it, we can talk about configurations after that ;)

**Comment by theorywrong** [comment]
First, Dialog or Window (like mp3 player, hex editor) style ?

**Comment by TheOfficialFloW** [comment]
Big dialog style, where entries are assigned to left and options to the right side. That's how I imagine it

**Comment by WesleyPolicena** [comment]
suggestion...

![example01](https://cloud.githubusercontent.com/assets/21372797/18800584/267e7982-81b4-11e6-8470-518081c95726.png)
![example02](https://cloud.githubusercontent.com/assets/21372797/18800585/2683bac8-81b4-11e6-9567-e158139311a9.png)

**Comment by WesleyPolicena** [comment]
L1/R1 to navigate between tabs

**Comment by TheOfficialFloW** [comment]
I like that

**Comment by WesleyPolicena** [comment]
icons for a cleaner look

https://design.google.com/icons/

**Comment by theorywrong** [comment]
Humm, maybe remplace the list dialog toolbox by your context menu

**Comment by WesleyPolicena** [comment]
let the context menu only for actions with the selected file / folder

![example03](https://cloud.githubusercontent.com/assets/21372797/18802326/789b7c42-81be-11e6-803a-960ae7d1e864.png)

**Comment by WesleyPolicena** [comment]
![example04](https://cloud.githubusercontent.com/assets/21372797/18803315/5a692754-81c5-11e6-8cef-97699214e966.png)
![example05](https://cloud.githubusercontent.com/assets/21372797/18803316/5a697344-81c5-11e6-8beb-001ec4c8138f.png)

**Comment by WesleyPolicena** [comment]
and more...

![example06](https://cloud.githubusercontent.com/assets/21372797/18804567/0f401856-81d3-11e6-99ee-55d6b6f566f5.png)

**Comment by TheOfficialFloW** [comment]
I don't want to have the context menu in the center.

**Comment by theorywrong** [comment]
maybe not to do too much on design? no ?

**Comment by WesleyPolicena** [comment]
![example08](https://cloud.githubusercontent.com/assets/21372797/18808551/c7214392-823b-11e6-9db0-af603dd5f4b5.png)

**Comment by WesleyPolicena** [comment]
![example07](https://cloud.githubusercontent.com/assets/21372797/18808928/25d3e610-8246-11e6-8a0f-c538fd4ef7c4.gif)

**Comment by WesleyPolicena** [comment]
![example08](https://cloud.githubusercontent.com/assets/21372797/18809417/f95482ba-8250-11e6-9554-097c5fcfcc34.gif)

**Comment by BigBoot** [comment]
What do you guys think:
Instantly apply changes or have a apply/cancel button?

I kinda prefer instant apply, what about you?

**Comment by TheOfficialFloW** [comment]
Yes, instant apply is better

**Comment by WesleyPolicena** [comment]
Yes, instant apply is better

**Comment by littlebalup** [comment]
Agree. With an option to retore to default.

**Comment by limyz** [comment]
Instant apply is cool.

**Comment by BigBoot** [comment]
![2016-09-26-005209](https://cloud.githubusercontent.com/assets/1175520/18818789/bb2e2084-8383-11e6-9aac-bbbe0cb55028.jpg)

**Comment by WesleyPolicena** [comment]
wow that's cool

**Comment by WesleyPolicena** [comment]
Suggestion..

alignment ready to tap the screen

![exmple](https://cloud.githubusercontent.com/assets/21372797/18819171/570a7840-8361-11e6-915c-21f0f0cfc66f.gif)

**Comment by BigBoot** [comment]
I don't get it, when would it slide out/in?

**Comment by WesleyPolicena** [comment]
Display only when you open the window

**Comment by WesleyPolicena** [comment]
or static, like in most apps

**Comment by limyz** [comment]
That's way too much UI. Follow good UI/UX practices. @BigBoot You may want to note that @TheOfficialFloW doesn't want the context menu in the center.

**Comment by BigBoot** [comment]
But that's not the context menu...

**Comment by limyz** [comment]
My bad lol

**Comment by TheOfficialFloW** [comment]
Looks good. Maybe a slide in/out from top would feel great

**Comment by WesleyPolicena** [comment]
Some progress?
I'm looking forward to it :)

**Comment by theorywrong** [comment]
@BigBoot you have assigned this jobs, you have advanced?

**Comment by WesleyPolicena** [comment]
A minimalist idea...

![example12](https://cloud.githubusercontent.com/assets/21372797/18966208/c02f6e6e-8656-11e6-896c-727e97626d94.gif)

with a scroll bar, course!

**Comment by WesleyPolicena** [comment]
Map:
[Title (aligned center)]
[(Right justified) option] / [value (left-aligned)]
[(Right justified) option] / [value (left-aligned)]
space
...

Pressing the button: 
Switch between true / false, or open the text editing in the current selection

**Comment by TheOfficialFloW** [comment]
I really like your suggestion, thanks! Althouhh @BigBoot 's design is already great, I'd definitely see this implemented

**Comment by BigBoot** [comment]
I'm sorry I didn't have any time to work on it, 

I've pushed the current progress to a new [settings branch](/TheOfficialFlow/VitaShell/tree/settings)
Here's a compiled version of that branch: 
[VitaShell.zip](https://github.com/TheOfficialFloW/VitaShell/files/502965/VitaShell.zip)

**Comment by theorywrong** [comment]
great ! maybe find all language in the VitaShell folder like theme

**Comment by coderobe** [comment]
I feel like @WesleyPolicena's last suggestion is a bit too minimalist. The big dialog that was suggested before fits better to the dialogs that are already in the app

**Comment by coderobe** [comment]
Is there anything currently in progress? the settings branch seems very outdated by now

**Comment by theorywrong** [comment]
i prefer the minimalist idea, without the menu context in the left (personally)

**Comment by WesleyPolicena** [comment]
my suggestion is not to replace the right context menu, it would just be a menu drawer that appear when you press "Start", a launcher to give access to configurations, music player and others, replacing the current toolbox.

**Comment by WesleyPolicena** [comment]
It would be cool an option to start the FTP with Vitashell

**Comment by TheOfficialFloW** [comment]
:)
![2016-10-31-181512](https://cloud.githubusercontent.com/assets/14246466/19864139/39534474-9f97-11e6-874c-d29fa1fec82b.jpg)

**Comment by coderobe** [comment]
Does that make https://github.com/TheOfficialFloW/VitaShell/tree/settings deprecated then? Or is that supposed to be an extra menu?

**Comment by TheOfficialFloW** [comment]
Yeah. We should integrate some parts of it though. Now guys, help me adding real configurations
